spring:
  application:
    name: tracking-service

aws:
  ssm:
    region: ap-south-1

mongodb:
  uri: /Fittrack/mongodb/uri
  database: /Fittrack/mongodb/database

rabbitmq:
  uri: /Fittrack/rabbitmq/uri
  queue:
    activity-queue: activity_queue
    nutrition-queue: nutrition_queue
  exchange:
    name: fitness_exchange
    type: topic
  routing-key:
    activity-routing-key: activity_routing_key
    nutrition-routing-key: nutrition_routing_key

logging:
  level:
    org.springframework.boot.autoconfigure.mongo: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8072

