spring:
  application:
    name: activity-service

mongodb:
  uri: /Fittrack/ai-srvc/mongodb/uri
  database: /Fittrack/ai-srvc/mongodb/database

rabbitmq:
  addresses: /Fittrack/rabbitmq/addresses
  ssl:
    enabled: true

logging:
  level:
    org.springframework.boot.autoconfigure.mongo: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8072
